### PR TITLE
Revising Behat Example and Docs.

### PR DESCRIPTION
**Pull request by mikemadison13**
This update is based on the real life example i see in https://github.com/acquia/lightning

### CODE REVIEW

**Comment by mikemadison13** [comment]
odd @TravisCarden, let me keep poking at that. that methodology definitely worked for me in my distro (and it seems to be working in lightning).

**Comment by mikemadison13** [comment]
also @TravisCarden this may have broken because of composer caches. i had issues with the new composer autoloading i did until i flushed the travis cache.

**Comment by mikemadison13** [comment]
note that i accidentally left the `paths` key out of defaults in the original PR so it wasn't autoloading in the feature context properly. appears to be working now

**Comment by TravisCarden** [comment]
Thanks, @mikemadison13! Merged.

**Pull request merged**
