### PR TITLE
ORCA-504: Remove amplitude

### PR DESCRIPTION
**Pull request by secretsayan**
Related to https://github.com/acquia/orca/pull/107

### CODE REVIEW

**Comment by secretsayan** [comment]
@TravisCarden : Shall we re-use https://github.com/acquia/orca/pull/107 and replace Amplitude with Domo or just remove Amplitude for now?

**Comment by TravisCarden** [comment]
Go ahead and just remove Amplitude right now, @secretsayan.

**Review by TravisCarden — CHANGES_REQUESTED** [review]
Missed one thing. I don't have push access to your fork to push my updates, so here's the fix with a couple of comment changes:

```diff
diff --git a/example/.github/workflows/orca.yml b/example/.github/workflows/orca.yml
index fd21d05..f513d2e 100644
--- a/example/.github/workflows/orca.yml
+++ b/example/.github/workflows/orca.yml
@@ -87,7 +87,7 @@ jobs:
       # @see https://github.com/acquia/orca/blob/main/docs/advanced-usage.md#ORCA_PHPCS_STANDARD
       # ORCA_PHPCS_STANDARD: AcquiaDrupalTransitional
       #
-      # To enable telemetry on cron runs, uncomment the following
+      # To enable telemetry on cron runs, uncomment the following line:
       # @see https://github.com/acquia/orca/blob/main/docs/advanced-usage.md#ORCA_TELEMETRY_ENABLE
       # ORCA_TELEMETRY_ENABLE: "TRUE"
       #
diff --git a/phan.php b/phan.php
index 36808d6..99178b7 100644
--- a/phan.php
+++ b/phan.php
@@ -25,7 +25,6 @@ return [
     'vendor/symfony/options-resolver',
     'vendor/symfony/process',
     'vendor/symfony/yaml',
-    'vendor/zumba/amplitude-php',
   ],

   'exclude_file_regex' => '@^vendor/.*/(tests?|Tests?)/@',
diff --git a/src/Helper/Log/TelemetryClient.php b/src/Helper/Log/TelemetryClient.php
index d449caa..08fa0b6 100644
--- a/src/Helper/Log/TelemetryClient.php
+++ b/src/Helper/Log/TelemetryClient.php
@@ -37,6 +37,7 @@ class TelemetryClient {
    *   attributes of the event.
    */
   public function logEvent(string $type, array $properties = []): void {
+    // No telemetry provider is currently integrated.
   }

 }
```

**Comment by secretsayan** [comment]
Access provided and sonarlint file deleted.

**Review by TravisCarden — APPROVED** [review]

**Pull request merged**
