### PR TITLE
Add Coveralls (coveralls.io) support

### PR DESCRIPTION
**Pull request by TravisCarden**

### CODE REVIEW

**Comment by grasmash** [comment]
Don't forget to add the badge to the README.md. :)

**Comment by wimleers** [comment]
Does this mean _every_ project using ORCA for testing gets code coverage tracking automatically? (Well, after updating the `.travis.yml` file of course.)

**Comment by TravisCarden** [comment]
That's the intent, @wimleers, but there is some disagreement at present whether or not this belongs in ORCA.

**Comment by wimleers** [comment]
Thanks for sharing that. Lots of good thoughts/concerns in that e-mail thread!

**Comment by TravisCarden** [comment]
This feature has been descoped. Closing.

**Pull request closed without merging**
